### ISSUE TITLE
Feature request: Encrypt Images

### ISSUE THREAD

**Issue by stonie08** [mindcruzer/pelican-encrypt-content#10]
I really like the idea of having encrypted pages for some use-cases. However, I noticed that while text and therefore the references to images are encrypted, the images themselves are not (and most of the time have quite deterministic filenames, which is not the fault of this plugin).
Therefore, it'd be awesome if also images (and maybe even other files) get encrypted and then decrypted on the client.

I'm not sure if this would work well with the other image plugins out there, but I wanted to share this idea as a feature request.

**Comment by RyanShaw-3083** [comment]
Hi @stonie08 
Have you tried to write the encoded picture (base64) directly to markdown?

**Comment by mindcruzer** [comment]
I'm too busy in general to work on something like this, but its a cool idea. As a workaround, I would try to add the image as a [data uri](https://en.wikipedia.org/wiki/Data_URI_scheme).
