### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by nphilou** [mindcruzer/pelican-encrypt-content#14]
Hey,

Pycryto is deprecated in 3.7 and incompatible with python 3.8 (https://github.com/dlitz/pycrypto/issues/283).

It could be easily replaced by PyCrytodome (https://github.com/Legrandin/pycryptodome) without extra code.

I've made the fix on my side (with some test fixes): https://github.com/nphilou/pelican-encrypt-content. Please let me know if you're still maintaining this repo.

**Comment by mindcruzer** [comment]
Thanks for the good work @nphilou! I didn't realize pycrypto had issues with v3.8. If you submit a PR I will merge
