### ISSUE TITLE
make html fails for pelican-octopress theme site

### ISSUE THREAD

**Issue by JohnGriffiths** [mindcruzer/pelican-encrypt-content#4]
Ok sorry to be a tad schizophrenic...but I'm now trying to use the encrypt plugin on a different site which uses the pelican-octopress theme. 

Here, `make html` is failing with the following error:

`CRITICAL: encrypt_content/content.html
  make: ***  [/home/fsuser/encrypt_pelican_octopress_test/output/index.html] Error 1`

The files in the pelican-octopress theme don't all seem to correspond to the ones described in the README of this repo. E.g., there are quite a few files in an `_include` subdirectory. Not sure if that is the problem here or not. 

Any thoughts?

Thanks very much, 

john

**Comment by mindcruzer** [comment]
Make sure `encrypt_content/content.html` corresponds to an actual file in your themes `templates` directory. The file should be available if the `theme` folder was merged with your project's theme folder. Take note that I did modify the locations of the template files earlier today. They are now in `theme/templates/encrypt_content/` to keep things more organized, so make sure you are using the latest version or readme might be out of sync with the version you have cloned.

It is possible that a custom theme will use different template names. Unfortunately, if this is the case, you'll need to search around the templates to find out where the actual article content is being output. The key is to find those two template variables `{{ article.content }}` and `{{ article.summary }}` and modify as per the readme.
